var express = require('express');
var router = express.Router();
var mongo = require('mongodb');
var monk = require('monk');
var db = monk('localhost:27017/streaming_db_v');
var moment = require('moment');
var co = require('co');

// countries = new Object({//     "AF": { name: "Afghanistan" },
//     "AX": { name: "Åland Islands" },
//     "AL": { name: "Albania" },
//     "DZ": { name: "Algeria" },
//     "AS": { name: "American Samoa" },
//     "AD": { name: "Andorra" },
//     "AO": { name: "Angola" },
//     "AI": { name: "Anguilla" },
//     "AQ": { name: "Antarctica" },
//     "AG": { name: "Antigua and Barbuda" },
//     "AR": { name: "Argentina" },
//     "AM": { name: "Armenia" },
//     "AW": { name: "Aruba" },
//     "AU": { name: "Australia" },
//     "AT": { name: "Austria" },
//     "AZ": { name: "Azerbaijan" },
//     "BS": { name: "Bahamas" },
//     "BH": { name: "Bahrain" },
//     "BD": { name: "Bangladesh" },
//     "BB": { name: "Barbados" },
//     "BY": { name: "Belarus" },
//     "BE": { name: "Belgium" },
//     "BZ": { name: "Belize" },
//     "BJ": { name: "Benin" },
//     "BM": { name: "Bermuda" },
//     "BT": { name: "Bhutan" },
//     "BO": { name: "Bolivia" },
//     "BA": { name: "Bosnia and Herzegovina" },
//     "BW": { name: "Botswana" },
//     "BV": { name: "Bouvet Island" },
//     "BR": { name: "Brazil" },
//     "IO": { name: "British Indian Ocean Territory" },
//     "BN": { name: "Brunei Darussalam" },
//     "BG": { name: "Bulgaria" },
//     "BF": { name: "Burkina Faso" },
//     "BI": { name: "Burundi" },
//     "KH": { name: "Cambodia" },
//     "CM": { name: "Cameroon" },
//     "CA": { name: "Canada" },
//     "CV": { name: "Cape Verde" },
//     "KY": { name: "Cayman Islands" },
//     "CF": { name: "Central African Republic" },
//     "TD": { name: "Chad" },
//     "CL": { name: "Chile" },
//     "CN": { name: "China" },
//     "CX": { name: "Christmas Island" },
//     "CC": { name: "Cocos (Keeling) Islands" },
//     "CO": { name: "Colombia" },
//     "KM": { name: "Comoros" },
//     "CG": { name: "Congo" },
//     "CD": { name: "Congo, The Democratic Republic of the" },
//     "CK": { name: "Cook Islands" },
//     "CR": { name: "Costa Rica" },
//     "CI": { name: "Cote D'Ivoire" },
//     "HR": { name: "Croatia" },
//     "CU": { name: "Cuba" },
//     "CY": { name: "Cyprus" },
//     "CZ": { name: "Czech Republic" },
//     "DK": { name: "Denmark" },
//     "DJ": { name: "Djibouti" },
//     "DM": { name: "Dominica" },
//     "DO": { name: "Dominican Republic" },
//     "EC": { name: "Ecuador" },
//     "EG": { name: "Egypt" },
//     "SV": { name: "El Salvador" },
//     "GQ": { name: "Equatorial Guinea" },
//     "ER": { name: "Eritrea" },
//     "EE": { name: "Estonia" },
//     "ET": { name: "Ethiopia" },
//     "FK": { name: "Falkland Islands (Malvinas)" },
//     "FO": { name: "Faroe Islands" },
//     "FJ": { name: "Fiji" },
//     "FI": { name: "Finland" },
//     "FR": { name: "France" },
//     "GF": { name: "French Guiana" },
//     "PF": { name: "French Polynesia" },
//     "TF": { name: "French Southern Territories" },
//     "GA": { name: "Gabon" },
//     "GM": { name: "Gambia" },
//     "GE": { name: "Georgia" },
//     "DE": { name: "Germany" },
//     "GH": { name: "Ghana" },
//     "GI": { name: "Gibraltar" },
//     "GR": { name: "Greece" },
//     "GL": { name: "Greenland" },
//     "GD": { name: "Grenada" },
//     "GP": { name: "Guadeloupe" },
//     "GU": { name: "Guam" },
//     "GT": { name: "Guatemala" },
//     "GG": { name: "Guernsey" },
//     "GN": { name: "Guinea" },
//     "GW": { name: "Guinea-Bissau" },
//     "GY": { name: "Guyana" },
//     "HT": { name: "Haiti" },
//     "HM": { name: "Heard Island and Mcdonald Islands" },
//     "VA": { name: "Holy See (Vatican City State)" },
//     "HN": { name: "Honduras" },
//     "HK": { name: "Hong Kong" },
//     "HU": { name: "Hungary" },
//     "IS": { name: "Iceland" },
//     "IN": { name: "India" },
//     "ID": { name: "Indonesia" },
//     "IR": { name: "Iran, Islamic Republic Of" },
//     "IQ": { name: "Iraq" },
//     "IE": { name: "Ireland" },
//     "IM": { name: "Isle of Man" },
//     "IL": { name: "Israel" },
//     "IT": { name: "Italy" },
//     "JM": { name: "Jamaica" },
//     "JP": { name: "Japan" },
//     "JE": { name: "Jersey" },
//     "JO": { name: "Jordan" },
//     "KZ": { name: "Kazakhstan" },
//     "KE": { name: "Kenya" },
//     "KI": { name: "Kiribati" },
//     "KP": { name: "Democratic People's Republic of Korea" },
//     "KR": { name: "Korea, Republic of" },
//     "XK": { name: "Kosovo" },
//     "KW": { name: "Kuwait" },
//     "KG": { name: "Kyrgyzstan" },
//     "LA": { name: "Lao People's Democratic Republic" },
//     "LV": { name: "Latvia" },
//     "LB": { name: "Lebanon" },
//     "LS": { name: "Lesotho" },
//     "LR": { name: "Liberia" },
//     "LY": { name: "Libyan Arab Jamahiriya" },
//     "LI": { name: "Liechtenstein" },
//     "LT": { name: "Lithuania" },
//     "LU": { name: "Luxembourg" },
//     "MO": { name: "Macao" },
//     "MK": { name: "Macedonia, The Former Yugoslav Republic of" },
//     "MG": { name: "Madagascar" },
//     "MW": { name: "Malawi" },
//     "MY": { name: "Malaysia" },
//     "MV": { name: "Maldives" },
//     "ML": { name: "Mali" },
//     "MT": { name: "Malta" },
//     "MH": { name: "Marshall Islands" },
//     "MQ": { name: "Martinique" },
//     "MR": { name: "Mauritania" },
//     "MU": { name: "Mauritius" },
//     "YT": { name: "Mayotte" },
//     "MX": { name: "Mexico" },
//     "FM": { name: "Micronesia, Federated States of" },
//     "MD": { name: "Moldova, Republic of" },
//     "MC": { name: "Monaco" },
//     "MN": { name: "Mongolia" },
//     "ME": { name: "Montenegro" },
//     "MS": { name: "Montserrat" },
//     "MA": { name: "Morocco" },
//     "MZ": { name: "Mozambique" },
//     "MM": { name: "Myanmar" },
//     "NA": { name: "Namibia" },
//     "NR": { name: "Nauru" },
//     "NP": { name: "Nepal" },
//     "NL": { name: "Netherlands" },
//     "AN": { name: "Netherlands Antilles" },
//     "NC": { name: "New Caledonia" },
//     "NZ": { name: "New Zealand" },
//     "NI": { name: "Nicaragua" },
//     "NE": { name: "Niger" },
//     "NG": { name: "Nigeria" },
//     "NU": { name: "Niue" },
//     "NF": { name: "Norfolk Island" },
//     "MP": { name: "Northern Mariana Islands" },
//     "NO": { name: "Norway" },
//     "OM": { name: "Oman" },
//     "PK": { name: "Pakistan" },
//     "PW": { name: "Palau" },
//     "PS": { name: "Palestinian Territory, Occupied" },
//     "PA": { name: "Panama" },
//     "PG": { name: "Papua New Guinea" },
//     "PY": { name: "Paraguay" },
//     "PE": { name: "Peru" },
//     "PH": { name: "Philippines" },
//     "PN": { name: "Pitcairn" },
//     "PL": { name: "Poland" },
//     "PT": { name: "Portugal" },
//     "PR": { name: "Puerto Rico" },
//     "QA": { name: "Qatar" },
//     "RE": { name: "Reunion" },
//     "RO": { name: "Romania" },
//     "RU": { name: "Russian Federation" },
//     "RW": { name: "Rwanda" },
//     "SH": { name: "Saint Helena" },
//     "KN": { name: "Saint Kitts and Nevis" },
//     "LC": { name: "Saint Lucia" },
//     "PM": { name: "Saint Pierre and Miquelon" },
//     "VC": { name: "Saint Vincent and the Grenadines" },
//     "WS": { name: "Samoa" },
//     "SM": { name: "San Marino" },
//     "ST": { name: "Sao Tome and Principe" },
//     "SA": { name: "Saudi Arabia" },
//     "SN": { name: "Senegal" },
//     "RS": { name: "Serbia" },
//     "SC": { name: "Seychelles" },
//     "SL": { name: "Sierra Leone" },
//     "SG": { name: "Singapore" },
//     "SK": { name: "Slovakia" },
//     "SI": { name: "Slovenia" },
//     "SB": { name: "Solomon Islands" },
//     "SO": { name: "Somalia" },
//     "ZA": { name: "South Africa" },
//     "GS": { name: "South Georgia and the South Sandwich Islands" },
//     "ES": { name: "Spain" },
//     "LK": { name: "Sri Lanka" },
//     "SD": { name: "Sudan" },
//     "SR": { name: "Suriname" },
//     "SJ": { name: "Svalbard and Jan Mayen" },
//     "SZ": { name: "Swaziland" },
//     "SE": { name: "Sweden" },
//     "CH": { name: "Switzerland" },
//     "SY": { name: "Syrian Arab Republic" },
//     "TW": { name: "Taiwan" },
//     "TJ": { name: "Tajikistan" },
//     "TZ": { name: "Tanzania, United Republic of" },
//     "TH": { name: "Thailand" },
//     "TL": { name: "Timor-Leste" },
//     "TG": { name: "Togo" },
//     "TK": { name: "Tokelau" },
//     "TO": { name: "Tonga" },
//     "TT": { name: "Trinidad and Tobago" },
//     "TN": { name: "Tunisia" },
//     "TR": { name: "Turkey" },
//     "TM": { name: "Turkmenistan" },
//     "TC": { name: "Turks and Caicos Islands" },
//     "TV": { name: "Tuvalu" },
//     "UG": { name: "Uganda" },
//     "UA": { name: "Ukraine" },
//     "AE": { name: "United Arab Emirates" },
//     "GB": { name: "United Kingdom" },
//     "US": { name: "United States" },
//     "UM": { name: "United States Minor Outlying Islands" },
//     "UY": { name: "Uruguay" },
//     "UZ": { name: "Uzbekistan" },
//     "VU": { name: "Vanuatu" },
//     "VE": { name: "Venezuela" },
//     "VN": { name: "Viet Nam" },
//     "VG": { name: "Virgin Islands, British" },
//     "VI": { name: "Virgin Islands, U.S." },
//     "WF": { name: "Wallis and Futuna" },
//     "EH": { name: "Western Sahara" },
//     "YE": { name: "Yemen" },
//     "ZM": { name: "Zambia" },
//     "ZW": { name: "Zimbabwe" }
// });
var final = [
    { name: 'Afghanistan', value: 0 },
    { name: 'Angola', value: 0 },
    { name: 'Albania', value: 0 },
    { name: 'United Arab Emirates', value: 0 },
    { name: 'Argentina', value: 0 },
    { name: 'Armenia', value: 0 },
    { name: 'French Southern and Antarctic Lands', value: 0 },
    { name: 'Australia', value: 0 },
    { name: 'Austria', value: 0 },
    { name: 'Azerbaijan', value: 0 },
    { name: 'Burundi', value: 0 },
    { name: 'Belgium', value: 0 },
    { name: 'Benin', value: 0 },
    { name: 'Burkina Faso', value: 0 },
    { name: 'Bangladesh', value: 0 },
    { name: 'Bulgaria', value: 0 },
    { name: 'The Bahamas', value: 0 },
    { name: 'Bosnia and Herzegovina', value: 0 },
    { name: 'Belarus', value: 0 },
    { name: 'Belize', value: 0 },
    { name: 'Bermuda', value: 0 },
    { name: 'Bolivia', value: 0 },
    { name: 'Brazil', value: 0 },
    { name: 'Brunei', value: 0 },
    { name: 'Bhutan', value: 0 },
    { name: 'Botswana', value: 0 },
    { name: 'Central African Rep.', value: 0 },
    { name: 'Canada', value: 0 },
    { name: 'Switzerland', value: 0 },
    { name: 'Chile', value: 0 },
    { name: 'China', value: 0 },
    { name: 'Ivory Coast', value: 0 },
    { name: 'Cameroon', value: 0 },
    { name: 'Dem. Rep. Congo', value: 0 },
    { name: 'Congo', value: 0 },
    { name: 'Colombia', value: 0 },
    { name: 'Costa Rica', value: 0 },
    { name: 'Cuba', value: 0 },
    { name: 'Northern Cyprus', value: 0 },
    { name: 'Cyprus', value: 0 },
    { name: 'Czech Republic', value: 0 },
    { name: 'Germany', value: 0 },
    { name: 'Djibouti', value: 0 },
    { name: 'Denmark', value: 0 },
    { name: 'Dominican Republic', value: 0 },
    { name: 'Algeria', value: 0 },
    { name: 'Ecuador', value: 0 },
    { name: 'Egypt', value: 0 },
    { name: 'Eritrea', value: 0 },
    { name: 'Spain', value: 0 },
    { name: 'Estonia', value: 0 },
    { name: 'Ethiopia', value: 0 },
    { name: 'Finland', value: 0 },
    { name: 'Fiji', value: 0 },
    { name: 'Falkland Islands', value: 0 },
    { name: 'France', value: 0 },
    { name: 'Gabon', value: 0 },
    { name: 'United Kingdom', value: 0 },
    { name: 'Georgia', value: 0 },
    { name: 'Ghana', value: 0 },
    { name: 'Guinea', value: 0 },
    { name: 'Gambia', value: 0 },
    { name: 'Guinea Bissau', value: 0 },
    { name: 'Equatorial Guinea', value: 0 },
    { name: 'Greece', value: 0 },
    { name: 'Greenland', value: 0 },
    { name: 'Guatemala', value: 0 },
    { name: 'French Guiana', value: 0 },
    { name: 'Guyana', value: 0 },
    { name: 'Honduras', value: 0 },
    { name: 'Croatia', value: 0 },
    { name: 'Haiti', value: 0 },
    { name: 'Hungary', value: 0 },
    { name: 'Indonesia', value: 0 },
    { name: 'India', value: 0 },
    { name: 'Ireland', value: 0 },
    { name: 'Iran', value: 0 },
    { name: 'Iraq', value: 0 },
    { name: 'Iceland', value: 0 },
    { name: 'Israel', value: 0 },
    { name: 'Italy', value: 0 },
    { name: 'Jamaica', value: 0 },
    { name: 'Jordan', value: 0 },
    { name: 'Japan', value: 0 },
    { name: 'Kazakhstan', value: 0 },
    { name: 'Kenya', value: 0 },
    { name: 'Kyrgyzstan', value: 0 },
    { name: 'Cambodia', value: 0 },
    { name: 'Korea', value: 0 },
    { name: 'Kosovo', value: 0 },
    { name: 'Kuwait', value: 0 },
    { name: 'Laos', value: 0 },
    { name: 'Lebanon', value: 0 },
    { name: 'Liberia', value: 0 },
    { name: 'Libya', value: 0 },
    { name: 'Sri Lanka', value: 0 },
    { name: 'Lesotho', value: 0 },
    { name: 'Lithuania', value: 0 },
    { name: 'Luxembourg', value: 0 },
    { name: 'Latvia', value: 0 },
    { name: 'Morocco', value: 0 },
    { name: 'Moldova', value: 0 },
    { name: 'Madagascar', value: 0 },
    { name: 'Mexico', value: 0 },
    { name: 'Macedonia', value: 0 },
    { name: 'Mali', value: 0 },
    { name: 'Myanmar', value: 0 },
    { name: 'Montenegro', value: 0 },
    { name: 'Mongolia', value: 0 },
    { name: 'Mozambique', value: 0 },
    { name: 'Mauritania', value: 0 },
    { name: 'Malawi', value: 0 },
    { name: 'Malaysia', value: 0 },
    { name: 'Namibia', value: 0 },
    { name: 'New Caledonia', value: 0 },
    { name: 'Niger', value: 0 },
    { name: 'Nigeria', value: 0 },
    { name: 'Nicaragua', value: 0 },
    { name: 'Netherlands', value: 0 },
    { name: 'Norway', value: 0 },
    { name: 'Nepal', value: 0 },
    { name: 'New Zealand', value: 0 },
    { name: 'Oman', value: 0 },
    { name: 'Pakistan', value: 0 },
    { name: 'Panama', value: 0 },
    { name: 'Peru', value: 0 },
    { name: 'Philippines', value: 0 },
    { name: 'Papua New Guinea', value: 0 },
    { name: 'Poland', value: 0 },
    { name: 'Puerto Rico', value: 0 },
    { name: 'Dem. Rep. Korea', value: 0 },
    { name: 'Portugal', value: 0 },
    { name: 'Paraguay', value: 0 },
    { name: 'Qatar', value: 0 },
    { name: 'Romania', value: 0 },
    { name: 'Russia', value: 0 },
    { name: 'Rwanda', value: 0 },
    { name: 'W. Sahara', value: 0 },
    { name: 'Saudi Arabia', value: 0 },
    { name: 'Sudan', value: 0 },
    { name: 'S. Sudan', value: 0 },
    { name: 'Senegal', value: 0 },
    { name: 'Solomon Islands', value: 0 },
    { name: 'Sierra Leone', value: 0 },
    { name: 'El Salvador', value: 0 },
    { name: 'Somaliland', value: 0 },
    { name: 'Somalia', value: 0 },
    { name: 'Republic of Serbia', value: 0 },
    { name: 'Suriname', value: 0 },
    { name: 'Slovakia', value: 0 },
    { name: 'Slovenia', value: 0 },
    { name: 'Sweden', value: 0 },
    { name: 'Swaziland', value: 0 },
    { name: 'Syria', value: 0 },
    { name: 'Chad', value: 0 },
    { name: 'Togo', value: 0 },
    { name: 'Thailand', value: 0 },
    { name: 'Tajikistan', value: 0 },
    { name: 'Turkmenistan', value: 0 },
    { name: 'East Timor', value: 0 },
    { name: 'Trinidad and Tobago', value: 0 },
    { name: 'Tunisia', value: 0 },
    { name: 'Turkey', value: 0 },
    { name: 'Tanzania', value: 0 },
    { name: 'Uganda', value: 0 },
    { name: 'Ukraine', value: 0 },
    { name: 'Uruguay', value: 0 },
    { name: 'United States', value: 0 },
    { name: 'Uzbekistan', value: 0 },
    { name: 'Venezuela', value: 0 },
    { name: 'Vietnam', value: 0 },
    { name: 'Vanuatu', value: 0 },
    { name: 'West Bank', value: 0 },
    { name: 'Yemen', value: 0 },
    { name: 'South Africa', value: 0 },
    { name: 'Zambia', value: 0 },
    { name: 'Zimbabwe', value: 0 },
    { name: "CÃ´te d'Ivoire", value: 0 },
    { name: 'Dominican Rep', value: 0 }
];
var data = [
    { name: 'Afghanistan', value: 0 },
    { name: 'Angola', value: 0 },
    { name: 'Albania', value: 0 },
    { name: 'United Arab Emirates', value: 0 },
    { name: 'Argentina', value: 0 },
    { name: 'Armenia', value: 0 },
    { name: 'French Southern and Antarctic Lands', value: 0 },
    { name: 'Australia', value: 0 },
    { name: 'Austria', value: 0 },
    { name: 'Azerbaijan', value: 0 },
    { name: 'Burundi', value: 0 },
    { name: 'Belgium', value: 0 },
    { name: 'Benin', value: 0 },
    { name: 'Burkina Faso', value: 0 },
    { name: 'Bangladesh', value: 0 },
    { name: 'Bulgaria', value: 0 },
    { name: 'The Bahamas', value: 0 },
    { name: 'Bosnia and Herzegovina', value: 0 },
    { name: 'Belarus', value: 0 },
    { name: 'Belize', value: 0 },
    { name: 'Bermuda', value: 0 },
    { name: 'Bolivia', value: 0 },
    { name: 'Brazil', value: 0 },
    { name: 'Brunei', value: 0 },
    { name: 'Bhutan', value: 0 },
    { name: 'Botswana', value: 0 },
    { name: 'Central African Rep.', value: 0 },
    { name: 'Canada', value: 0 },
    { name: 'Switzerland', value: 0 },
    { name: 'Chile', value: 0 },
    { name: 'China', value: 0 },
    { name: 'Ivory Coast', value: 0 },
    { name: 'Cameroon', value: 0 },
    { name: 'Dem. Rep. Congo', value: 0 },
    { name: 'Congo', value: 0 },
    { name: 'Colombia', value: 0 },
    { name: 'Costa Rica', value: 0 },
    { name: 'Cuba', value: 0 },
    { name: 'Northern Cyprus', value: 0 },
    { name: 'Cyprus', value: 0 },
    { name: 'Czech Republic', value: 0 },
    { name: 'Germany', value: 0 },
    { name: 'Djibouti', value: 0 },
    { name: 'Denmark', value: 0 },
    { name: 'Dominican Republic', value: 0 },
    { name: 'Algeria', value: 0 },
    { name: 'Ecuador', value: 0 },
    { name: 'Egypt', value: 0 },
    { name: 'Eritrea', value: 0 },
    { name: 'Spain', value: 0 },
    { name: 'Estonia', value: 0 },
    { name: 'Ethiopia', value: 0 },
    { name: 'Finland', value: 0 },
    { name: 'Fiji', value: 0 },
    { name: 'Falkland Islands', value: 0 },
    { name: 'France', value: 0 },
    { name: 'Gabon', value: 0 },
    { name: 'United Kingdom', value: 0 },
    { name: 'Georgia', value: 0 },
    { name: 'Ghana', value: 0 },
    { name: 'Guinea', value: 0 },
    { name: 'Gambia', value: 0 },
    { name: 'Guinea Bissau', value: 0 },
    { name: 'Equatorial Guinea', value: 0 },
    { name: 'Greece', value: 0 },
    { name: 'Greenland', value: 0 },
    { name: 'Guatemala', value: 0 },
    { name: 'French Guiana', value: 0 },
    { name: 'Guyana', value: 0 },
    { name: 'Honduras', value: 0 },
    { name: 'Croatia', value: 0 },
    { name: 'Haiti', value: 0 },
    { name: 'Hungary', value: 0 },
    { name: 'Indonesia', value: 0 },
    { name: 'India', value: 0 },
    { name: 'Ireland', value: 0 },
    { name: 'Iran', value: 0 },
    { name: 'Iraq', value: 0 },
    { name: 'Iceland', value: 0 },
    { name: 'Israel', value: 0 },
    { name: 'Italy', value: 0 },
    { name: 'Jamaica', value: 0 },
    { name: 'Jordan', value: 0 },
    { name: 'Japan', value: 0 },
    { name: 'Kazakhstan', value: 0 },
    { name: 'Kenya', value: 0 },
    { name: 'Kyrgyzstan', value: 0 },
    { name: 'Cambodia', value: 0 },
    { name: 'Korea', value: 0 },
    { name: 'Kosovo', value: 0 },
    { name: 'Kuwait', value: 0 },
    { name: 'Laos', value: 0 },
    { name: 'Lebanon', value: 0 },
    { name: 'Liberia', value: 0 },
    { name: 'Libya', value: 0 },
    { name: 'Sri Lanka', value: 0 },
    { name: 'Lesotho', value: 0 },
    { name: 'Lithuania', value: 0 },
    { name: 'Luxembourg', value: 0 },
    { name: 'Latvia', value: 0 },
    { name: 'Morocco', value: 0 },
    { name: 'Moldova', value: 0 },
    { name: 'Madagascar', value: 0 },
    { name: 'Mexico', value: 0 },
    { name: 'Macedonia', value: 0 },
    { name: 'Mali', value: 0 },
    { name: 'Myanmar', value: 0 },
    { name: 'Montenegro', value: 0 },
    { name: 'Mongolia', value: 0 },
    { name: 'Mozambique', value: 0 },
    { name: 'Mauritania', value: 0 },
    { name: 'Malawi', value: 0 },
    { name: 'Malaysia', value: 0 },
    { name: 'Namibia', value: 0 },
    { name: 'New Caledonia', value: 0 },
    { name: 'Niger', value: 0 },
    { name: 'Nigeria', value: 0 },
    { name: 'Nicaragua', value: 0 },
    { name: 'Netherlands', value: 0 },
    { name: 'Norway', value: 0 },
    { name: 'Nepal', value: 0 },
    { name: 'New Zealand', value: 0 },
    { name: 'Oman', value: 0 },
    { name: 'Pakistan', value: 0 },
    { name: 'Panama', value: 0 },
    { name: 'Peru', value: 0 },
    { name: 'Philippines', value: 0 },
    { name: 'Papua New Guinea', value: 0 },
    { name: 'Poland', value: 0 },
    { name: 'Puerto Rico', value: 0 },
    { name: 'Dem. Rep. Korea', value: 0 },
    { name: 'Portugal', value: 0 },
    { name: 'Paraguay', value: 0 },
    { name: 'Qatar', value: 0 },
    { name: 'Romania', value: 0 },
    { name: 'Russia', value: 0 },
    { name: 'Rwanda', value: 0 },
    { name: 'W. Sahara', value: 0 },
    { name: 'Saudi Arabia', value: 0 },
    { name: 'Sudan', value: 0 },
    { name: 'S. Sudan', value: 0 },
    { name: 'Senegal', value: 0 },
    { name: 'Solomon Islands', value: 0 },
    { name: 'Sierra Leone', value: 0 },
    { name: 'El Salvador', value: 0 },
    { name: 'Somaliland', value: 0 },
    { name: 'Somalia', value: 0 },
    { name: 'Republic of Serbia', value: 0 },
    { name: 'Suriname', value: 0 },
    { name: 'Slovakia', value: 0 },
    { name: 'Slovenia', value: 0 },
    { name: 'Sweden', value: 0 },
    { name: 'Swaziland', value: 0 },
    { name: 'Syria', value: 0 },
    { name: 'Chad', value: 0 },
    { name: 'Togo', value: 0 },
    { name: 'Thailand', value: 0 },
    { name: 'Tajikistan', value: 0 },
    { name: 'Turkmenistan', value: 0 },
    { name: 'East Timor', value: 0 },
    { name: 'Trinidad and Tobago', value: 0 },
    { name: 'Tunisia', value: 0 },
    { name: 'Turkey', value: 0 },
    { name: 'Tanzania', value: 0 },
    { name: 'Uganda', value: 0 },
    { name: 'Ukraine', value: 0 },
    { name: 'Uruguay', value: 0 },
    { name: 'United States', value: 0 },
    { name: 'Uzbekistan', value: 0 },
    { name: 'Venezuela', value: 0 },
    { name: 'Vietnam', value: 0 },
    { name: 'Vanuatu', value: 0 },
    { name: 'West Bank', value: 0 },
    { name: 'Yemen', value: 0 },
    { name: 'South Africa', value: 0 },
    { name: 'Zambia', value: 0 },
    { name: 'Zimbabwe', value: 0 },
    { name: "CÃ´te d'Ivoire", value: 0 },
    { name: 'Dominican Rep', value: 0 }
];
var tweets = db.get('tweets');
//var country = Object.keys(countries);


function* getCountriesTweets(start, end, callback) {
    //var countryTweets = new Object();

    var time = "2017-09-12T19:43:31Z";
    // use 'yield' to freeze the for loop until tweets.count is finished
    // it's a simple way to de-asyncronized function, but this will introduce
    // more running time. And also, remember to make the function as a generator function
    // by adding a * after the function keyword.
    // Last, use co module to control the whole process. see line 304.
    //db.tweets.find({"_createdDate":{$gte:new Date("2017-09-11T19:43:31Z")}}).count()
    // yield tweets.count({"_createdDate":{$gte:new Date(start),$lte:new Date(end)},"place.country":final[i].name}, function(err, count) {
    //     console.log(count);
    //     data[i]={name:final[i].name,value:count}
    //     // countryTweets[country[i]] = count;
    // });//db.tweets.aggregate([{$match:{"_createdDate":{$gt:new Date("2017-09-15T19:43:31Z")}}},{$group:{_id:"$place.country_code",total:{$sum:"$_negEmoji"}}}])
    for (var i = 0; i < final.length; i++) {
        yield tweets.aggregate([{
                $match: { "_createdDate": { $gt: new Date(start), $lt: new Date(end) }, "place.country": data[i].name }
            },
            {
                $group: {
                    _id: "$place.country_code",
                    negValue: { $sum: "$_negEmoji" },
                    posValue: { $sum: "$_posEmoji" }
                }
            }
        ]).then((res) => {
            //final[55].value=res[0].value;
            if (res[0]) {
                console.log(res);
                if (res[0].posValue != 0) {
                    final[i].value = (res[0].negValue) / (res[0].posValue);
                    console.log(final[i].value);
                } else {
                    final[i].value = res[0].negValue;
                }
            }
        });
    }

    //  var Pos = new array();
    //  var Neg = new array();
    //  yield tweets.find({"_createdDate":{$gte:new Date(start),$lte:new Date(end)},"place.country":final[i].name}, function(err, count) {
    //      console.log(count);
    //      Neg[i]=count;
    //
    //  });
    // yield tweets.count({"_createdDate":{$gte:new Date(start),$lte:new Date(end)},"place.country":final[i].name,"_emotion":"Neg"}, function(err, count) {
    //          console.log(count);
    //          data[i]={name:final[i].name,negValue:count}
    //          // countryTweets[country[i]] = count;
    //      });
    //  data[i]={name:final[i].name,value: pos[i]/neg[i]};

    //}
    callback(final);
}

function getTimeInterval(time) {
    var t = new Date(); //你已知的时间
    var t_s = t.getTime(); //转化为时间戳毫秒数
    t.setTime(t_s - time * 1000 * 60 * 60); //设置新时间比旧时间多一小时
    return t;
}
/* GET home page. */
router.get('/', function(req, res, next) {
    var start = Number(req.query.start);
    var end = Number(req.query.end);
    var startTime = getTimeInterval(start);
    var endTime = getTimeInterval(end);
    console.log(startTime + endTime)
    //
    co(getCountriesTweets(startTime, endTime, function(data) {
        res.send(final);
    }));
    //res.send(final);
    // });

});

module.exports = router;